source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.1.0'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'rails', '4.2.4'
gem 'sass-rails', '~> 5.0'
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'spring'
  gem 'web-console', '~> 2.0'
end

group :development, :test do
  gem 'pry-byebug' # debugger
  gem 'pry-rails'  # sets pry as default REPL for `rails c`
end

group :doc do
  gem 'sdoc', '~> 0.4.0'
end
