# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56fd575d5411c5d9e234946ed55a1553e0c0b7f404e92045060ad0e344814fd8c4fb8b5b07a559f0022219433c68826537f6fcf3b83f71ef35d2c1387bfce233

test:
  secret_key_base: 2b2b29bf75937679f91af215ab549b1cd39f58b6f9cb804bbb1c6c7801413f7a60b2419a235a0b2b0fc9c9817cac127978c6e9db929007b327d3668945e032dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
